# /*

PROJECT: E-Commerce SQL Case Study
FILE: analysis.sql

DESCRIPTION:
This file contains business analysis queries used to
generate insights from the E-Commerce database.

TOPICS COVERED:

1. Customer Order Analysis
2. Customer Spending Analysis
3. Revenue Analysis
4. Payment Method Analysis
5. Product Performance Analysis
6. Product Revenue Analysis
7. Category Performance Analysis
   =========================================================
   */

# /*

TOPIC: Customer Order Analysis

QUESTION:
Show all customers and their orders.

PURPOSE:
Retrieve customer information along with their order
details and current order status.

BUSINESS USE:
Track customer purchases, monitor order fulfillment,
and support customer service operations.

EXPECTED INSIGHT:
Identify customers with multiple orders and gain
visibility into order statuses across the business.
===================================================

*/

SELECT
c.customer_name,
o.order_id,
o.order_date,
o.order_status
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id;

# /*

TOPIC: Customer Spending Analysis

QUESTION:
How much money has each customer spent?

PURPOSE:
Calculate the total amount spent by each customer
across all completed purchases.

BUSINESS USE:
Identify high-value customers for loyalty programs,
customer retention initiatives, and targeted marketing
campaigns.

EXPECTED INSIGHT:
Customers with the highest spending contribute the
most revenue and may qualify as premium customers.
==================================================

*/

SELECT
c.customer_name,
SUM(p.amount) AS total_spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_name
ORDER BY total_spent DESC;

# /*

TOPIC: Revenue Analysis

QUESTION:
What is the total revenue generated by the business?

PURPOSE:
Calculate the overall revenue generated from all
customer payments.

BUSINESS USE:
Measure business performance, track sales growth,
and evaluate financial health.

EXPECTED INSIGHT:
Provides a high-level view of total earnings generated
during the analysis period.
===========================

*/

SELECT
SUM(amount) AS total_revenue
FROM payments;

# /*

TOPIC: Payment Method Analysis

QUESTION:
Which payment methods generate the most revenue?

PURPOSE:
Calculate revenue contribution from each payment
method.

BUSINESS USE:
Understand customer payment preferences and support
decisions related to payment gateway optimization.

EXPECTED INSIGHT:
The most frequently used payment method is likely to
contribute the highest share of revenue.
========================================

*/

SELECT
payment_method,
SUM(amount) AS revenue
FROM payments
GROUP BY payment_method
ORDER BY revenue DESC;

# /*

TOPIC: Product Performance Analysis

QUESTION:
Which products sold the highest quantity?

PURPOSE:
Calculate the total quantity sold for each product.

BUSINESS USE:
Identify best-selling products and support inventory
planning, procurement, and stock replenishment.

EXPECTED INSIGHT:
Products with the highest quantity sold represent the
strongest customer demand.
==========================

*/

SELECT
p.product_name,
SUM(oi.quantity) AS total_quantity_sold
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC;

# /*

TOPIC: Product Revenue Analysis

QUESTION:
Which products generated the highest revenue?

PURPOSE:
Calculate total revenue generated by each product.

BUSINESS USE:
Identify products contributing the most revenue and
support pricing, marketing, and sales strategies.

EXPECTED INSIGHT:
High-revenue products are key contributors to overall
business profitability.
=======================

*/

SELECT
p.product_name,
SUM(oi.quantity * oi.price_per_unit) AS revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
ORDER BY revenue DESC;

# /*

TOPIC: Category Performance Analysis

QUESTION:
Which product categories generate the highest revenue?

PURPOSE:
Calculate total revenue generated by each product
category.

BUSINESS USE:
Evaluate category-level performance and support
business decisions regarding inventory allocation,
marketing budgets, and expansion opportunities.

EXPECTED INSIGHT:
Top-performing categories indicate where customer
demand and profitability are concentrated.
==========================================

*/

SELECT
p.category,
SUM(oi.quantity * oi.price_per_unit) AS revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY revenue DESC;
