# /*

PROJECT: E-Commerce SQL Case Study
FILE: ctes.sql

DESCRIPTION:
This file demonstrates the use of Common Table
Expressions (CTEs) to simplify complex SQL queries
and improve readability.

SQL CONCEPTS COVERED:

1. Common Table Expressions (CTEs)
2. Aggregation
3. Reusable Query Logic
4. Business Analysis using Temporary Result Sets

BUSINESS OBJECTIVE:
Generate customer, product, and category insights
using reusable analytical datasets.
===================================

*/

# /*

TOPIC: Customer Spending Analysis

QUESTION:
How much has each customer spent?

PURPOSE:
Calculate total spending for every customer.

BUSINESS USE:
Supports customer segmentation, loyalty program
planning, and customer value analysis.

EXPECTED INSIGHT:
Customers with higher spending contribute more
significantly to business revenue.
==================================

*/

WITH customer_spending AS
(
SELECT
c.customer_name,
SUM(p.amount) AS total_spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_name
)

SELECT *
FROM customer_spending
ORDER BY total_spent DESC;

# /*

TOPIC: Highest Spending Customer Analysis

QUESTION:
Who is the highest spending customer?

PURPOSE:
Identify the customer generating the maximum revenue.

BUSINESS USE:
Supports VIP customer identification and customer
retention strategies.

EXPECTED INSIGHT:
The returned customer represents the highest-value
customer in the dataset.
========================

*/

WITH customer_spending AS
(
SELECT
c.customer_name,
SUM(p.amount) AS total_spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN payments p
ON o.order_id = p.order_id
GROUP BY c.customer_name
)

SELECT *
FROM customer_spending
WHERE total_spent =
(
SELECT MAX(total_spent)
FROM customer_spending
);

# /*

TOPIC: Category Revenue Analysis

QUESTION:
How much revenue is generated by each product
category?

PURPOSE:
Calculate category-wise revenue contribution.

BUSINESS USE:
Supports category performance evaluation and
inventory planning decisions.

EXPECTED INSIGHT:
Categories generating higher revenue represent key
business growth opportunities.
==============================

*/

WITH category_revenue AS
(
SELECT
p.category,
SUM(oi.quantity * oi.price_per_unit) AS revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.category
)

SELECT *
FROM category_revenue
ORDER BY revenue DESC;

# /*

TOPIC: High Revenue Category Analysis

QUESTION:
Which categories generate more than ₹10,000
in revenue?

PURPOSE:
Identify categories exceeding a defined revenue
threshold.

BUSINESS USE:
Supports investment decisions and category-focused
marketing initiatives.

EXPECTED INSIGHT:
Categories returned by the query are major revenue
contributors.
=============

*/

WITH category_revenue AS
(
SELECT
p.category,
SUM(oi.quantity * oi.price_per_unit) AS revenue
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.category
)

SELECT *
FROM category_revenue
WHERE revenue > 10000;

# /*

TOPIC: Product Sales Analysis

QUESTION:
Which products sold the highest number of units?

PURPOSE:
Calculate total units sold for each product.

BUSINESS USE:
Supports inventory planning and product demand
forecasting.

EXPECTED INSIGHT:
Products with higher sales volumes represent stronger
customer demand.
================

*/

WITH product_sales AS
(
SELECT
p.product_name,
SUM(oi.quantity) AS total_units_sold
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
)

SELECT *
FROM product_sales
ORDER BY total_units_sold DESC;

# /*

TOPIC: Top-Selling Product Analysis

QUESTION:
Which product sold the highest number of units?

PURPOSE:
Identify the most frequently purchased product.

BUSINESS USE:
Supports inventory prioritization and product
promotion strategies.

EXPECTED INSIGHT:
The returned product represents the strongest-selling
item in the catalog.
====================

*/

WITH product_sales AS
(
SELECT
p.product_name,
SUM(oi.quantity) AS total_units_sold
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_name
)

SELECT *
FROM product_sales
WHERE total_units_sold =
(
SELECT MAX(total_units_sold)
FROM product_sales
);
